# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct RoCrateEntitiesApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `RoCrateEntitiesApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ RoCrateEntitiesApi }) = "http://localhost/torc-service/v1"

const _returntypes_create_ro_crate_entity_RoCrateEntitiesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => RoCrateEntityModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("422", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_create_ro_crate_entity(_api::RoCrateEntitiesApi, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_ro_crate_entity_RoCrateEntitiesApi, "/ro_crate_entities", [], ro_crate_entity_model)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- ro_crate_entity_model::RoCrateEntityModel (required)

Return: RoCrateEntityModel, OpenAPI.Clients.ApiResponse
"""
function create_ro_crate_entity(_api::RoCrateEntitiesApi, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = _oacinternal_create_ro_crate_entity(_api, ro_crate_entity_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_ro_crate_entity(_api::RoCrateEntitiesApi, response_stream::Channel, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = _oacinternal_create_ro_crate_entity(_api, ro_crate_entity_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_ro_crate_entities_RoCrateEntitiesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DeleteRoCrateEntitiesResponse,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_delete_ro_crate_entities(_api::RoCrateEntitiesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_ro_crate_entities_RoCrateEntitiesApi, "/workflows/{id}/ro_crate_entities", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: DeleteRoCrateEntitiesResponse, OpenAPI.Clients.ApiResponse
"""
function delete_ro_crate_entities(_api::RoCrateEntitiesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_ro_crate_entities(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_ro_crate_entities(_api::RoCrateEntitiesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_ro_crate_entities(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_ro_crate_entity_RoCrateEntitiesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => MessageResponse,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_delete_ro_crate_entity(_api::RoCrateEntitiesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_ro_crate_entity_RoCrateEntitiesApi, "/ro_crate_entities/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: MessageResponse, OpenAPI.Clients.ApiResponse
"""
function delete_ro_crate_entity(_api::RoCrateEntitiesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_ro_crate_entity(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_ro_crate_entity(_api::RoCrateEntitiesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_ro_crate_entity(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_ro_crate_entity_RoCrateEntitiesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => RoCrateEntityModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_get_ro_crate_entity(_api::RoCrateEntitiesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_ro_crate_entity_RoCrateEntitiesApi, "/ro_crate_entities/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: RoCrateEntityModel, OpenAPI.Clients.ApiResponse
"""
function get_ro_crate_entity(_api::RoCrateEntitiesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_ro_crate_entity(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_ro_crate_entity(_api::RoCrateEntitiesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_ro_crate_entity(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_ro_crate_entities_RoCrateEntitiesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ListRoCrateEntitiesResponse,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_list_ro_crate_entities(_api::RoCrateEntitiesApi, id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_ro_crate_entities_RoCrateEntitiesApi, "/workflows/{id}/ro_crate_entities", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "limit", limit; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "sort_by", sort_by; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "reverse_sort", reverse_sort; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- offset::Int64
- limit::Int64
- sort_by::String
- reverse_sort::Bool

Return: ListRoCrateEntitiesResponse, OpenAPI.Clients.ApiResponse
"""
function list_ro_crate_entities(_api::RoCrateEntitiesApi, id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_ro_crate_entities(_api, id; offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_ro_crate_entities(_api::RoCrateEntitiesApi, response_stream::Channel, id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_ro_crate_entities(_api, id; offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_ro_crate_entity_RoCrateEntitiesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => RoCrateEntityModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("422", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_update_ro_crate_entity(_api::RoCrateEntitiesApi, id::Int64, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_ro_crate_entity_RoCrateEntitiesApi, "/ro_crate_entities/{id}", [], ro_crate_entity_model)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- ro_crate_entity_model::RoCrateEntityModel (required)

Return: RoCrateEntityModel, OpenAPI.Clients.ApiResponse
"""
function update_ro_crate_entity(_api::RoCrateEntitiesApi, id::Int64, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = _oacinternal_update_ro_crate_entity(_api, id, ro_crate_entity_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_ro_crate_entity(_api::RoCrateEntitiesApi, response_stream::Channel, id::Int64, ro_crate_entity_model::RoCrateEntityModel; _mediaType=nothing)
    _ctx = _oacinternal_update_ro_crate_entity(_api, id, ro_crate_entity_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_ro_crate_entity
export delete_ro_crate_entities
export delete_ro_crate_entity
export get_ro_crate_entity
export list_ro_crate_entities
export update_ro_crate_entity
