# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct SlurmSchedulersApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `SlurmSchedulersApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ SlurmSchedulersApi }) = "http://localhost/torc-service/v1"

const _returntypes_create_slurm_scheduler_SlurmSchedulersApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SlurmSchedulerModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_create_slurm_scheduler(_api::SlurmSchedulersApi, slurm_scheduler_model::SlurmSchedulerModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_slurm_scheduler_SlurmSchedulersApi, "/slurm_schedulers", [], slurm_scheduler_model)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- slurm_scheduler_model::SlurmSchedulerModel (required)

Return: SlurmSchedulerModel, OpenAPI.Clients.ApiResponse
"""
function create_slurm_scheduler(_api::SlurmSchedulersApi, slurm_scheduler_model::SlurmSchedulerModel; _mediaType=nothing)
    _ctx = _oacinternal_create_slurm_scheduler(_api, slurm_scheduler_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_slurm_scheduler(_api::SlurmSchedulersApi, response_stream::Channel, slurm_scheduler_model::SlurmSchedulerModel; _mediaType=nothing)
    _ctx = _oacinternal_create_slurm_scheduler(_api, slurm_scheduler_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_slurm_scheduler_SlurmSchedulersApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SlurmSchedulerModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_delete_slurm_scheduler(_api::SlurmSchedulersApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_slurm_scheduler_SlurmSchedulersApi, "/slurm_schedulers/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: SlurmSchedulerModel, OpenAPI.Clients.ApiResponse
"""
function delete_slurm_scheduler(_api::SlurmSchedulersApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_slurm_scheduler(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_slurm_scheduler(_api::SlurmSchedulersApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_slurm_scheduler(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_slurm_schedulers_SlurmSchedulersApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DeleteCountResponse,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_delete_slurm_schedulers(_api::SlurmSchedulersApi, workflow_id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_slurm_schedulers_SlurmSchedulersApi, "/slurm_schedulers", [])
    OpenAPI.Clients.set_param(_ctx.query, "workflow_id", workflow_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- workflow_id::Int64 (required)

Return: DeleteCountResponse, OpenAPI.Clients.ApiResponse
"""
function delete_slurm_schedulers(_api::SlurmSchedulersApi, workflow_id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_slurm_schedulers(_api, workflow_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_slurm_schedulers(_api::SlurmSchedulersApi, response_stream::Channel, workflow_id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_slurm_schedulers(_api, workflow_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_slurm_scheduler_SlurmSchedulersApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SlurmSchedulerModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_get_slurm_scheduler(_api::SlurmSchedulersApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_slurm_scheduler_SlurmSchedulersApi, "/slurm_schedulers/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: SlurmSchedulerModel, OpenAPI.Clients.ApiResponse
"""
function get_slurm_scheduler(_api::SlurmSchedulersApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_slurm_scheduler(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_slurm_scheduler(_api::SlurmSchedulersApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_slurm_scheduler(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_slurm_schedulers_SlurmSchedulersApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ListSlurmSchedulersResponse,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_list_slurm_schedulers(_api::SlurmSchedulersApi, workflow_id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_slurm_schedulers_SlurmSchedulersApi, "/slurm_schedulers", [])
    OpenAPI.Clients.set_param(_ctx.query, "workflow_id", workflow_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "limit", limit; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "sort_by", sort_by; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "reverse_sort", reverse_sort; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- workflow_id::Int64 (required)
- offset::Int64
- limit::Int64
- sort_by::String
- reverse_sort::Bool

Return: ListSlurmSchedulersResponse, OpenAPI.Clients.ApiResponse
"""
function list_slurm_schedulers(_api::SlurmSchedulersApi, workflow_id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_slurm_schedulers(_api, workflow_id; offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_slurm_schedulers(_api::SlurmSchedulersApi, response_stream::Channel, workflow_id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_slurm_schedulers(_api, workflow_id; offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_slurm_scheduler_SlurmSchedulersApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SlurmSchedulerModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_update_slurm_scheduler(_api::SlurmSchedulersApi, id::Int64, slurm_scheduler_model::SlurmSchedulerModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_slurm_scheduler_SlurmSchedulersApi, "/slurm_schedulers/{id}", [], slurm_scheduler_model)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- slurm_scheduler_model::SlurmSchedulerModel (required)

Return: SlurmSchedulerModel, OpenAPI.Clients.ApiResponse
"""
function update_slurm_scheduler(_api::SlurmSchedulersApi, id::Int64, slurm_scheduler_model::SlurmSchedulerModel; _mediaType=nothing)
    _ctx = _oacinternal_update_slurm_scheduler(_api, id, slurm_scheduler_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_slurm_scheduler(_api::SlurmSchedulersApi, response_stream::Channel, id::Int64, slurm_scheduler_model::SlurmSchedulerModel; _mediaType=nothing)
    _ctx = _oacinternal_update_slurm_scheduler(_api, id, slurm_scheduler_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_slurm_scheduler
export delete_slurm_scheduler
export delete_slurm_schedulers
export get_slurm_scheduler
export list_slurm_schedulers
export update_slurm_scheduler
