# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct UserDataApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `UserDataApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ UserDataApi }) = "http://localhost/torc-service/v1"

const _returntypes_create_user_data_UserDataApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => UserDataModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_create_user_data(_api::UserDataApi, user_data_model::UserDataModel; consumer_job_id=nothing, producer_job_id=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_user_data_UserDataApi, "/user_data", [], user_data_model)
    OpenAPI.Clients.set_param(_ctx.query, "consumer_job_id", consumer_job_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "producer_job_id", producer_job_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- user_data_model::UserDataModel (required)
- consumer_job_id::Int64
- producer_job_id::Int64

Return: UserDataModel, OpenAPI.Clients.ApiResponse
"""
function create_user_data(_api::UserDataApi, user_data_model::UserDataModel; consumer_job_id=nothing, producer_job_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_create_user_data(_api, user_data_model; consumer_job_id=consumer_job_id, producer_job_id=producer_job_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_user_data(_api::UserDataApi, response_stream::Channel, user_data_model::UserDataModel; consumer_job_id=nothing, producer_job_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_create_user_data(_api, user_data_model; consumer_job_id=consumer_job_id, producer_job_id=producer_job_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_all_user_data_UserDataApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Any,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_delete_all_user_data(_api::UserDataApi, workflow_id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_all_user_data_UserDataApi, "/user_data", [])
    OpenAPI.Clients.set_param(_ctx.query, "workflow_id", workflow_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- workflow_id::Int64 (required)

Return: Any, OpenAPI.Clients.ApiResponse
"""
function delete_all_user_data(_api::UserDataApi, workflow_id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_all_user_data(_api, workflow_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_all_user_data(_api::UserDataApi, response_stream::Channel, workflow_id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_all_user_data(_api, workflow_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_user_data_UserDataApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => UserDataModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_delete_user_data(_api::UserDataApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_user_data_UserDataApi, "/user_data/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: UserDataModel, OpenAPI.Clients.ApiResponse
"""
function delete_user_data(_api::UserDataApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_user_data(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_user_data(_api::UserDataApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_user_data(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_user_data_UserDataApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => UserDataModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_get_user_data(_api::UserDataApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_user_data_UserDataApi, "/user_data/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: UserDataModel, OpenAPI.Clients.ApiResponse
"""
function get_user_data(_api::UserDataApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_user_data(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_user_data(_api::UserDataApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_user_data(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_user_data_UserDataApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ListUserDataResponse,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_list_user_data(_api::UserDataApi, workflow_id::Int64; consumer_job_id=nothing, producer_job_id=nothing, offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, name=nothing, is_ephemeral=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_user_data_UserDataApi, "/user_data", [])
    OpenAPI.Clients.set_param(_ctx.query, "workflow_id", workflow_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "consumer_job_id", consumer_job_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "producer_job_id", producer_job_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "limit", limit; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "sort_by", sort_by; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "reverse_sort", reverse_sort; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_param(_ctx.query, "name", name; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "is_ephemeral", is_ephemeral; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- workflow_id::Int64 (required)
- consumer_job_id::Int64
- producer_job_id::Int64
- offset::Int64
- limit::Int64
- sort_by::String
- reverse_sort::Bool
- name::String
- is_ephemeral::Bool

Return: ListUserDataResponse, OpenAPI.Clients.ApiResponse
"""
function list_user_data(_api::UserDataApi, workflow_id::Int64; consumer_job_id=nothing, producer_job_id=nothing, offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, name=nothing, is_ephemeral=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_user_data(_api, workflow_id; consumer_job_id=consumer_job_id, producer_job_id=producer_job_id, offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, name=name, is_ephemeral=is_ephemeral, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_user_data(_api::UserDataApi, response_stream::Channel, workflow_id::Int64; consumer_job_id=nothing, producer_job_id=nothing, offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, name=nothing, is_ephemeral=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_user_data(_api, workflow_id; consumer_job_id=consumer_job_id, producer_job_id=producer_job_id, offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, name=name, is_ephemeral=is_ephemeral, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_user_data_UserDataApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => UserDataModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_update_user_data(_api::UserDataApi, id::Int64, user_data_model::UserDataModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_user_data_UserDataApi, "/user_data/{id}", [], user_data_model)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- user_data_model::UserDataModel (required)

Return: UserDataModel, OpenAPI.Clients.ApiResponse
"""
function update_user_data(_api::UserDataApi, id::Int64, user_data_model::UserDataModel; _mediaType=nothing)
    _ctx = _oacinternal_update_user_data(_api, id, user_data_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_user_data(_api::UserDataApi, response_stream::Channel, id::Int64, user_data_model::UserDataModel; _mediaType=nothing)
    _ctx = _oacinternal_update_user_data(_api, id, user_data_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_user_data
export delete_all_user_data
export delete_user_data
export get_user_data
export list_user_data
export update_user_data
