# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct RemoteWorkersApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `RemoteWorkersApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ RemoteWorkersApi }) = "http://localhost/torc-service/v1"

const _returntypes_create_remote_workers_RemoteWorkersApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{RemoteWorkerModel},
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("422", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_create_remote_workers(_api::RemoteWorkersApi, id::Int64, request_body::Vector{String}; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_remote_workers_RemoteWorkersApi, "/workflows/{id}/remote_workers", [], request_body)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- request_body::Vector{String} (required)

Return: Vector{RemoteWorkerModel}, OpenAPI.Clients.ApiResponse
"""
function create_remote_workers(_api::RemoteWorkersApi, id::Int64, request_body::Vector{String}; _mediaType=nothing)
    _ctx = _oacinternal_create_remote_workers(_api, id, request_body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_remote_workers(_api::RemoteWorkersApi, response_stream::Channel, id::Int64, request_body::Vector{String}; _mediaType=nothing)
    _ctx = _oacinternal_create_remote_workers(_api, id, request_body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_remote_worker_RemoteWorkersApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => RemoteWorkerModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_delete_remote_worker(_api::RemoteWorkersApi, id::Int64, worker::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_remote_worker_RemoteWorkersApi, "/workflows/{id}/remote_workers/{worker}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_param(_ctx.path, "worker", worker)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- worker::String (required)

Return: RemoteWorkerModel, OpenAPI.Clients.ApiResponse
"""
function delete_remote_worker(_api::RemoteWorkersApi, id::Int64, worker::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_remote_worker(_api, id, worker; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_remote_worker(_api::RemoteWorkersApi, response_stream::Channel, id::Int64, worker::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_remote_worker(_api, id, worker; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_remote_workers_RemoteWorkersApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{RemoteWorkerModel},
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_list_remote_workers(_api::RemoteWorkersApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_remote_workers_RemoteWorkersApi, "/workflows/{id}/remote_workers", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: Vector{RemoteWorkerModel}, OpenAPI.Clients.ApiResponse
"""
function list_remote_workers(_api::RemoteWorkersApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_list_remote_workers(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_remote_workers(_api::RemoteWorkersApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_list_remote_workers(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_remote_workers
export delete_remote_worker
export list_remote_workers
