# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct ComputeNodesApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `ComputeNodesApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ ComputeNodesApi }) = "http://localhost/torc-service/v1"

const _returntypes_create_compute_node_ComputeNodesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ComputeNodeModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_create_compute_node(_api::ComputeNodesApi, compute_node_model::ComputeNodeModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_compute_node_ComputeNodesApi, "/compute_nodes", [], compute_node_model)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- compute_node_model::ComputeNodeModel (required)

Return: ComputeNodeModel, OpenAPI.Clients.ApiResponse
"""
function create_compute_node(_api::ComputeNodesApi, compute_node_model::ComputeNodeModel; _mediaType=nothing)
    _ctx = _oacinternal_create_compute_node(_api, compute_node_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_compute_node(_api::ComputeNodesApi, response_stream::Channel, compute_node_model::ComputeNodeModel; _mediaType=nothing)
    _ctx = _oacinternal_create_compute_node(_api, compute_node_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_compute_node_ComputeNodesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ComputeNodeModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_delete_compute_node(_api::ComputeNodesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_compute_node_ComputeNodesApi, "/compute_nodes/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: ComputeNodeModel, OpenAPI.Clients.ApiResponse
"""
function delete_compute_node(_api::ComputeNodesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_compute_node(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_compute_node(_api::ComputeNodesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_compute_node(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_compute_nodes_ComputeNodesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DeleteCountResponse,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_delete_compute_nodes(_api::ComputeNodesApi, workflow_id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_compute_nodes_ComputeNodesApi, "/compute_nodes", [])
    OpenAPI.Clients.set_param(_ctx.query, "workflow_id", workflow_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- workflow_id::Int64 (required)

Return: DeleteCountResponse, OpenAPI.Clients.ApiResponse
"""
function delete_compute_nodes(_api::ComputeNodesApi, workflow_id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_compute_nodes(_api, workflow_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_compute_nodes(_api::ComputeNodesApi, response_stream::Channel, workflow_id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_compute_nodes(_api, workflow_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_compute_node_ComputeNodesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ComputeNodeModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_get_compute_node(_api::ComputeNodesApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_compute_node_ComputeNodesApi, "/compute_nodes/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)

Return: ComputeNodeModel, OpenAPI.Clients.ApiResponse
"""
function get_compute_node(_api::ComputeNodesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_compute_node(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_compute_node(_api::ComputeNodesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_compute_node(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_compute_nodes_ComputeNodesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ListComputeNodesResponse,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_list_compute_nodes(_api::ComputeNodesApi, workflow_id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, hostname=nothing, is_active=nothing, scheduled_compute_node_id=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_compute_nodes_ComputeNodesApi, "/compute_nodes", [])
    OpenAPI.Clients.set_param(_ctx.query, "workflow_id", workflow_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "limit", limit; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "sort_by", sort_by; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "reverse_sort", reverse_sort; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_param(_ctx.query, "hostname", hostname; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "is_active", is_active; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_param(_ctx.query, "scheduled_compute_node_id", scheduled_compute_node_id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- workflow_id::Int64 (required)
- offset::Int64
- limit::Int64
- sort_by::String
- reverse_sort::Bool
- hostname::String
- is_active::Bool
- scheduled_compute_node_id::Int64

Return: ListComputeNodesResponse, OpenAPI.Clients.ApiResponse
"""
function list_compute_nodes(_api::ComputeNodesApi, workflow_id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, hostname=nothing, is_active=nothing, scheduled_compute_node_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_compute_nodes(_api, workflow_id; offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, hostname=hostname, is_active=is_active, scheduled_compute_node_id=scheduled_compute_node_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_compute_nodes(_api::ComputeNodesApi, response_stream::Channel, workflow_id::Int64; offset=nothing, limit=nothing, sort_by=nothing, reverse_sort=nothing, hostname=nothing, is_active=nothing, scheduled_compute_node_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_compute_nodes(_api, workflow_id; offset=offset, limit=limit, sort_by=sort_by, reverse_sort=reverse_sort, hostname=hostname, is_active=is_active, scheduled_compute_node_id=scheduled_compute_node_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_compute_node_ComputeNodesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ComputeNodeModel,
    Regex("^" * replace("403", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => ErrorResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => ErrorResponse,
)

function _oacinternal_update_compute_node(_api::ComputeNodesApi, id::Int64, compute_node_model::ComputeNodeModel; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_compute_node_ComputeNodesApi, "/compute_nodes/{id}", [], compute_node_model)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::Int64 (required)
- compute_node_model::ComputeNodeModel (required)

Return: ComputeNodeModel, OpenAPI.Clients.ApiResponse
"""
function update_compute_node(_api::ComputeNodesApi, id::Int64, compute_node_model::ComputeNodeModel; _mediaType=nothing)
    _ctx = _oacinternal_update_compute_node(_api, id, compute_node_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_compute_node(_api::ComputeNodesApi, response_stream::Channel, id::Int64, compute_node_model::ComputeNodeModel; _mediaType=nothing)
    _ctx = _oacinternal_update_compute_node(_api, id, compute_node_model; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_compute_node
export delete_compute_node
export delete_compute_nodes
export get_compute_node
export list_compute_nodes
export update_compute_node
