# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListRequiredExistingFilesResponse

    ListRequiredExistingFilesResponse(;
        files=nothing,
    )

    - files::Vector{Int64}
"""
Base.@kwdef mutable struct ListRequiredExistingFilesResponse <: OpenAPI.APIModel
    files::Union{Nothing, Vector{Int64}} = nothing

    function ListRequiredExistingFilesResponse(files, )
        o = new(files, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ListRequiredExistingFilesResponse

const _property_types_ListRequiredExistingFilesResponse = Dict{Symbol,String}(Symbol("files")=>"Vector{Int64}", )
OpenAPI.property_type(::Type{ ListRequiredExistingFilesResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListRequiredExistingFilesResponse[name]))}

function OpenAPI.check_required(o::ListRequiredExistingFilesResponse)
    o.files === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ListRequiredExistingFilesResponse)
    OpenAPI.validate_property(ListRequiredExistingFilesResponse, Symbol("files"), o.files)
end

function OpenAPI.validate_property(::Type{ ListRequiredExistingFilesResponse }, name::Symbol, val)

end
