# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ClaimNextJobsResponse

    ClaimNextJobsResponse(;
        jobs=nothing,
    )

    - jobs::Vector{JobModel}
"""
Base.@kwdef mutable struct ClaimNextJobsResponse <: OpenAPI.APIModel
    jobs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobModel} }

    function ClaimNextJobsResponse(jobs, )
        o = new(jobs, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ClaimNextJobsResponse

const _property_types_ClaimNextJobsResponse = Dict{Symbol,String}(Symbol("jobs")=>"Vector{JobModel}", )
OpenAPI.property_type(::Type{ ClaimNextJobsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ClaimNextJobsResponse[name]))}

function OpenAPI.check_required(o::ClaimNextJobsResponse)
    true
end

function OpenAPI.validate_properties(o::ClaimNextJobsResponse)
    OpenAPI.validate_property(ClaimNextJobsResponse, Symbol("jobs"), o.jobs)
end

function OpenAPI.validate_property(::Type{ ClaimNextJobsResponse }, name::Symbol, val)

end
