# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MessageResponse

    MessageResponse(;
        message=nothing,
    )

    - message::String
"""
Base.@kwdef mutable struct MessageResponse <: OpenAPI.APIModel
    message::Union{Nothing, String} = nothing

    function MessageResponse(message, )
        o = new(message, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type MessageResponse

const _property_types_MessageResponse = Dict{Symbol,String}(Symbol("message")=>"String", )
OpenAPI.property_type(::Type{ MessageResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MessageResponse[name]))}

function OpenAPI.check_required(o::MessageResponse)
    o.message === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::MessageResponse)
    OpenAPI.validate_property(MessageResponse, Symbol("message"), o.message)
end

function OpenAPI.validate_property(::Type{ MessageResponse }, name::Symbol, val)

end
