# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RemoteWorkerModel

    RemoteWorkerModel(;
        worker=nothing,
        workflow_id=nothing,
    )

    - worker::String
    - workflow_id::Int64
"""
Base.@kwdef mutable struct RemoteWorkerModel <: OpenAPI.APIModel
    worker::Union{Nothing, String} = nothing
    workflow_id::Union{Nothing, Int64} = nothing

    function RemoteWorkerModel(worker, workflow_id, )
        o = new(worker, workflow_id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RemoteWorkerModel

const _property_types_RemoteWorkerModel = Dict{Symbol,String}(Symbol("worker")=>"String", Symbol("workflow_id")=>"Int64", )
OpenAPI.property_type(::Type{ RemoteWorkerModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RemoteWorkerModel[name]))}

function OpenAPI.check_required(o::RemoteWorkerModel)
    o.worker === nothing && (return false)
    o.workflow_id === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::RemoteWorkerModel)
    OpenAPI.validate_property(RemoteWorkerModel, Symbol("worker"), o.worker)
    OpenAPI.validate_property(RemoteWorkerModel, Symbol("workflow_id"), o.workflow_id)
end

function OpenAPI.validate_property(::Type{ RemoteWorkerModel }, name::Symbol, val)


    if name === Symbol("workflow_id")
        OpenAPI.validate_param(name, "RemoteWorkerModel", :format, val, "int64")
    end
end
