# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchCompleteJobsResponse

    BatchCompleteJobsResponse(;
        completed=nothing,
        errors=nothing,
    )

    - completed::Vector{Int64}
    - errors::Vector{JobCompletionError}
"""
Base.@kwdef mutable struct BatchCompleteJobsResponse <: OpenAPI.APIModel
    completed::Union{Nothing, Vector{Int64}} = nothing
    errors::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobCompletionError} }

    function BatchCompleteJobsResponse(completed, errors, )
        o = new(completed, errors, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type BatchCompleteJobsResponse

const _property_types_BatchCompleteJobsResponse = Dict{Symbol,String}(Symbol("completed")=>"Vector{Int64}", Symbol("errors")=>"Vector{JobCompletionError}", )
OpenAPI.property_type(::Type{ BatchCompleteJobsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchCompleteJobsResponse[name]))}

function OpenAPI.check_required(o::BatchCompleteJobsResponse)
    o.completed === nothing && (return false)
    o.errors === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::BatchCompleteJobsResponse)
    OpenAPI.validate_property(BatchCompleteJobsResponse, Symbol("completed"), o.completed)
    OpenAPI.validate_property(BatchCompleteJobsResponse, Symbol("errors"), o.errors)
end

function OpenAPI.validate_property(::Type{ BatchCompleteJobsResponse }, name::Symbol, val)


end
