# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""IsUninitializedResponse

    IsUninitializedResponse(;
        is_uninitialized=nothing,
    )

    - is_uninitialized::Bool
"""
Base.@kwdef mutable struct IsUninitializedResponse <: OpenAPI.APIModel
    is_uninitialized::Union{Nothing, Bool} = nothing

    function IsUninitializedResponse(is_uninitialized, )
        o = new(is_uninitialized, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type IsUninitializedResponse

const _property_types_IsUninitializedResponse = Dict{Symbol,String}(Symbol("is_uninitialized")=>"Bool", )
OpenAPI.property_type(::Type{ IsUninitializedResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IsUninitializedResponse[name]))}

function OpenAPI.check_required(o::IsUninitializedResponse)
    o.is_uninitialized === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::IsUninitializedResponse)
    OpenAPI.validate_property(IsUninitializedResponse, Symbol("is_uninitialized"), o.is_uninitialized)
end

function OpenAPI.validate_property(::Type{ IsUninitializedResponse }, name::Symbol, val)

end
