# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""WorkflowModel

    WorkflowModel(;
        compute_node_expiration_buffer_seconds=nothing,
        compute_node_ignore_workflow_completion=nothing,
        compute_node_min_time_for_new_jobs_seconds=nothing,
        compute_node_wait_for_healthy_database_minutes=nothing,
        compute_node_wait_for_new_jobs_seconds=nothing,
        description=nothing,
        enable_ro_crate=nothing,
        env=nothing,
        execution_config=nothing,
        id=nothing,
        metadata=nothing,
        name=nothing,
        project=nothing,
        resource_monitor_config=nothing,
        slurm_config=nothing,
        slurm_defaults=nothing,
        status_id=nothing,
        timestamp=nothing,
        use_pending_failed=nothing,
        user=nothing,
    )

    - compute_node_expiration_buffer_seconds::Int64
    - compute_node_ignore_workflow_completion::Bool
    - compute_node_min_time_for_new_jobs_seconds::Int64
    - compute_node_wait_for_healthy_database_minutes::Int64
    - compute_node_wait_for_new_jobs_seconds::Int64
    - description::String
    - enable_ro_crate::Bool
    - env::Dict{String, String}
    - execution_config::String
    - id::Int64
    - metadata::String
    - name::String
    - project::String
    - resource_monitor_config::String
    - slurm_config::String
    - slurm_defaults::String
    - status_id::Int64
    - timestamp::String
    - use_pending_failed::Bool
    - user::String
"""
Base.@kwdef mutable struct WorkflowModel <: OpenAPI.APIModel
    compute_node_expiration_buffer_seconds::Union{Nothing, Int64} = nothing
    compute_node_ignore_workflow_completion::Union{Nothing, Bool} = nothing
    compute_node_min_time_for_new_jobs_seconds::Union{Nothing, Int64} = nothing
    compute_node_wait_for_healthy_database_minutes::Union{Nothing, Int64} = nothing
    compute_node_wait_for_new_jobs_seconds::Union{Nothing, Int64} = nothing
    description::Union{Nothing, String} = nothing
    enable_ro_crate::Union{Nothing, Bool} = nothing
    env::Union{Nothing, Dict{String, String}} = nothing
    execution_config::Union{Nothing, String} = nothing
    id::Union{Nothing, Int64} = nothing
    metadata::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    project::Union{Nothing, String} = nothing
    resource_monitor_config::Union{Nothing, String} = nothing
    slurm_config::Union{Nothing, String} = nothing
    slurm_defaults::Union{Nothing, String} = nothing
    status_id::Union{Nothing, Int64} = nothing
    timestamp::Union{Nothing, String} = nothing
    use_pending_failed::Union{Nothing, Bool} = nothing
    user::Union{Nothing, String} = nothing

    function WorkflowModel(compute_node_expiration_buffer_seconds, compute_node_ignore_workflow_completion, compute_node_min_time_for_new_jobs_seconds, compute_node_wait_for_healthy_database_minutes, compute_node_wait_for_new_jobs_seconds, description, enable_ro_crate, env, execution_config, id, metadata, name, project, resource_monitor_config, slurm_config, slurm_defaults, status_id, timestamp, use_pending_failed, user, )
        o = new(compute_node_expiration_buffer_seconds, compute_node_ignore_workflow_completion, compute_node_min_time_for_new_jobs_seconds, compute_node_wait_for_healthy_database_minutes, compute_node_wait_for_new_jobs_seconds, description, enable_ro_crate, env, execution_config, id, metadata, name, project, resource_monitor_config, slurm_config, slurm_defaults, status_id, timestamp, use_pending_failed, user, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type WorkflowModel

const _property_types_WorkflowModel = Dict{Symbol,String}(Symbol("compute_node_expiration_buffer_seconds")=>"Int64", Symbol("compute_node_ignore_workflow_completion")=>"Bool", Symbol("compute_node_min_time_for_new_jobs_seconds")=>"Int64", Symbol("compute_node_wait_for_healthy_database_minutes")=>"Int64", Symbol("compute_node_wait_for_new_jobs_seconds")=>"Int64", Symbol("description")=>"String", Symbol("enable_ro_crate")=>"Bool", Symbol("env")=>"Dict{String, String}", Symbol("execution_config")=>"String", Symbol("id")=>"Int64", Symbol("metadata")=>"String", Symbol("name")=>"String", Symbol("project")=>"String", Symbol("resource_monitor_config")=>"String", Symbol("slurm_config")=>"String", Symbol("slurm_defaults")=>"String", Symbol("status_id")=>"Int64", Symbol("timestamp")=>"String", Symbol("use_pending_failed")=>"Bool", Symbol("user")=>"String", )
OpenAPI.property_type(::Type{ WorkflowModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowModel[name]))}

function OpenAPI.check_required(o::WorkflowModel)
    o.name === nothing && (return false)
    o.user === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::WorkflowModel)
    OpenAPI.validate_property(WorkflowModel, Symbol("compute_node_expiration_buffer_seconds"), o.compute_node_expiration_buffer_seconds)
    OpenAPI.validate_property(WorkflowModel, Symbol("compute_node_ignore_workflow_completion"), o.compute_node_ignore_workflow_completion)
    OpenAPI.validate_property(WorkflowModel, Symbol("compute_node_min_time_for_new_jobs_seconds"), o.compute_node_min_time_for_new_jobs_seconds)
    OpenAPI.validate_property(WorkflowModel, Symbol("compute_node_wait_for_healthy_database_minutes"), o.compute_node_wait_for_healthy_database_minutes)
    OpenAPI.validate_property(WorkflowModel, Symbol("compute_node_wait_for_new_jobs_seconds"), o.compute_node_wait_for_new_jobs_seconds)
    OpenAPI.validate_property(WorkflowModel, Symbol("description"), o.description)
    OpenAPI.validate_property(WorkflowModel, Symbol("enable_ro_crate"), o.enable_ro_crate)
    OpenAPI.validate_property(WorkflowModel, Symbol("env"), o.env)
    OpenAPI.validate_property(WorkflowModel, Symbol("execution_config"), o.execution_config)
    OpenAPI.validate_property(WorkflowModel, Symbol("id"), o.id)
    OpenAPI.validate_property(WorkflowModel, Symbol("metadata"), o.metadata)
    OpenAPI.validate_property(WorkflowModel, Symbol("name"), o.name)
    OpenAPI.validate_property(WorkflowModel, Symbol("project"), o.project)
    OpenAPI.validate_property(WorkflowModel, Symbol("resource_monitor_config"), o.resource_monitor_config)
    OpenAPI.validate_property(WorkflowModel, Symbol("slurm_config"), o.slurm_config)
    OpenAPI.validate_property(WorkflowModel, Symbol("slurm_defaults"), o.slurm_defaults)
    OpenAPI.validate_property(WorkflowModel, Symbol("status_id"), o.status_id)
    OpenAPI.validate_property(WorkflowModel, Symbol("timestamp"), o.timestamp)
    OpenAPI.validate_property(WorkflowModel, Symbol("use_pending_failed"), o.use_pending_failed)
    OpenAPI.validate_property(WorkflowModel, Symbol("user"), o.user)
end

function OpenAPI.validate_property(::Type{ WorkflowModel }, name::Symbol, val)

    if name === Symbol("compute_node_expiration_buffer_seconds")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end


    if name === Symbol("compute_node_min_time_for_new_jobs_seconds")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end

    if name === Symbol("compute_node_wait_for_healthy_database_minutes")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end

    if name === Symbol("compute_node_wait_for_new_jobs_seconds")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end




    if name === Symbol("id")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end







    if name === Symbol("status_id")
        OpenAPI.validate_param(name, "WorkflowModel", :format, val, "int64")
    end



end
