# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListMissingUserDataResponse

    ListMissingUserDataResponse(;
        user_data=nothing,
    )

    - user_data::Vector{Int64}
"""
Base.@kwdef mutable struct ListMissingUserDataResponse <: OpenAPI.APIModel
    user_data::Union{Nothing, Vector{Int64}} = nothing

    function ListMissingUserDataResponse(user_data, )
        o = new(user_data, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ListMissingUserDataResponse

const _property_types_ListMissingUserDataResponse = Dict{Symbol,String}(Symbol("user_data")=>"Vector{Int64}", )
OpenAPI.property_type(::Type{ ListMissingUserDataResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListMissingUserDataResponse[name]))}

function OpenAPI.check_required(o::ListMissingUserDataResponse)
    o.user_data === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ListMissingUserDataResponse)
    OpenAPI.validate_property(ListMissingUserDataResponse, Symbol("user_data"), o.user_data)
end

function OpenAPI.validate_property(::Type{ ListMissingUserDataResponse }, name::Symbol, val)

end
