# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""JobCompletionEntry

    JobCompletionEntry(;
        job_id=nothing,
        result=nothing,
        run_id=nothing,
        status=nothing,
    )

    - job_id::Int64
    - result::ResultModel
    - run_id::Int64
    - status::JobStatus
"""
Base.@kwdef mutable struct JobCompletionEntry <: OpenAPI.APIModel
    job_id::Union{Nothing, Int64} = nothing
    result = nothing # spec type: Union{ Nothing, ResultModel }
    run_id::Union{Nothing, Int64} = nothing
    status = nothing # spec type: Union{ Nothing, JobStatus }

    function JobCompletionEntry(job_id, result, run_id, status, )
        o = new(job_id, result, run_id, status, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type JobCompletionEntry

const _property_types_JobCompletionEntry = Dict{Symbol,String}(Symbol("job_id")=>"Int64", Symbol("result")=>"ResultModel", Symbol("run_id")=>"Int64", Symbol("status")=>"JobStatus", )
OpenAPI.property_type(::Type{ JobCompletionEntry }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_JobCompletionEntry[name]))}

function OpenAPI.check_required(o::JobCompletionEntry)
    o.job_id === nothing && (return false)
    o.result === nothing && (return false)
    o.run_id === nothing && (return false)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::JobCompletionEntry)
    OpenAPI.validate_property(JobCompletionEntry, Symbol("job_id"), o.job_id)
    OpenAPI.validate_property(JobCompletionEntry, Symbol("result"), o.result)
    OpenAPI.validate_property(JobCompletionEntry, Symbol("run_id"), o.run_id)
    OpenAPI.validate_property(JobCompletionEntry, Symbol("status"), o.status)
end

function OpenAPI.validate_property(::Type{ JobCompletionEntry }, name::Symbol, val)

    if name === Symbol("job_id")
        OpenAPI.validate_param(name, "JobCompletionEntry", :format, val, "int64")
    end


    if name === Symbol("run_id")
        OpenAPI.validate_param(name, "JobCompletionEntry", :format, val, "int64")
    end

end
