# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ReloadAuthResponse

    ReloadAuthResponse(;
        message=nothing,
        user_count=nothing,
    )

    - message::String
    - user_count::Int64
"""
Base.@kwdef mutable struct ReloadAuthResponse <: OpenAPI.APIModel
    message::Union{Nothing, String} = nothing
    user_count::Union{Nothing, Int64} = nothing

    function ReloadAuthResponse(message, user_count, )
        o = new(message, user_count, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ReloadAuthResponse

const _property_types_ReloadAuthResponse = Dict{Symbol,String}(Symbol("message")=>"String", Symbol("user_count")=>"Int64", )
OpenAPI.property_type(::Type{ ReloadAuthResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ReloadAuthResponse[name]))}

function OpenAPI.check_required(o::ReloadAuthResponse)
    o.message === nothing && (return false)
    o.user_count === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ReloadAuthResponse)
    OpenAPI.validate_property(ReloadAuthResponse, Symbol("message"), o.message)
    OpenAPI.validate_property(ReloadAuthResponse, Symbol("user_count"), o.user_count)
end

function OpenAPI.validate_property(::Type{ ReloadAuthResponse }, name::Symbol, val)


    if name === Symbol("user_count")
        OpenAPI.validate_param(name, "ReloadAuthResponse", :format, val, "int64")
    end
end
