# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateJobsResponse

    CreateJobsResponse(;
        jobs=nothing,
    )

    - jobs::Vector{JobModel}
"""
Base.@kwdef mutable struct CreateJobsResponse <: OpenAPI.APIModel
    jobs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobModel} }

    function CreateJobsResponse(jobs, )
        o = new(jobs, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type CreateJobsResponse

const _property_types_CreateJobsResponse = Dict{Symbol,String}(Symbol("jobs")=>"Vector{JobModel}", )
OpenAPI.property_type(::Type{ CreateJobsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateJobsResponse[name]))}

function OpenAPI.check_required(o::CreateJobsResponse)
    true
end

function OpenAPI.validate_properties(o::CreateJobsResponse)
    OpenAPI.validate_property(CreateJobsResponse, Symbol("jobs"), o.jobs)
end

function OpenAPI.validate_property(::Type{ CreateJobsResponse }, name::Symbol, val)

end
