# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UserDataModel

    UserDataModel(;
        data=nothing,
        id=nothing,
        is_ephemeral=nothing,
        name=nothing,
        workflow_id=nothing,
    )

    - data::Any
    - id::Int64
    - is_ephemeral::Bool
    - name::String
    - workflow_id::Int64
"""
Base.@kwdef mutable struct UserDataModel <: OpenAPI.APIModel
    data::Union{Nothing, Any} = nothing
    id::Union{Nothing, Int64} = nothing
    is_ephemeral::Union{Nothing, Bool} = nothing
    name::Union{Nothing, String} = nothing
    workflow_id::Union{Nothing, Int64} = nothing

    function UserDataModel(data, id, is_ephemeral, name, workflow_id, )
        o = new(data, id, is_ephemeral, name, workflow_id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type UserDataModel

const _property_types_UserDataModel = Dict{Symbol,String}(Symbol("data")=>"Any", Symbol("id")=>"Int64", Symbol("is_ephemeral")=>"Bool", Symbol("name")=>"String", Symbol("workflow_id")=>"Int64", )
OpenAPI.property_type(::Type{ UserDataModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UserDataModel[name]))}

function OpenAPI.check_required(o::UserDataModel)
    o.name === nothing && (return false)
    o.workflow_id === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::UserDataModel)
    OpenAPI.validate_property(UserDataModel, Symbol("data"), o.data)
    OpenAPI.validate_property(UserDataModel, Symbol("id"), o.id)
    OpenAPI.validate_property(UserDataModel, Symbol("is_ephemeral"), o.is_ephemeral)
    OpenAPI.validate_property(UserDataModel, Symbol("name"), o.name)
    OpenAPI.validate_property(UserDataModel, Symbol("workflow_id"), o.workflow_id)
end

function OpenAPI.validate_property(::Type{ UserDataModel }, name::Symbol, val)


    if name === Symbol("id")
        OpenAPI.validate_param(name, "UserDataModel", :format, val, "int64")
    end



    if name === Symbol("workflow_id")
        OpenAPI.validate_param(name, "UserDataModel", :format, val, "int64")
    end
end
