# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SlurmStatsModel

    SlurmStatsModel(;
        attempt_id=nothing,
        ave_cpu_seconds=nothing,
        id=nothing,
        job_id=nothing,
        max_disk_read_bytes=nothing,
        max_disk_write_bytes=nothing,
        max_rss_bytes=nothing,
        max_vm_size_bytes=nothing,
        node_list=nothing,
        run_id=nothing,
        slurm_job_id=nothing,
        workflow_id=nothing,
    )

    - attempt_id::Int64
    - ave_cpu_seconds::Float64
    - id::Int64
    - job_id::Int64
    - max_disk_read_bytes::Int64
    - max_disk_write_bytes::Int64
    - max_rss_bytes::Int64
    - max_vm_size_bytes::Int64
    - node_list::String
    - run_id::Int64
    - slurm_job_id::String
    - workflow_id::Int64
"""
Base.@kwdef mutable struct SlurmStatsModel <: OpenAPI.APIModel
    attempt_id::Union{Nothing, Int64} = nothing
    ave_cpu_seconds::Union{Nothing, Float64} = nothing
    id::Union{Nothing, Int64} = nothing
    job_id::Union{Nothing, Int64} = nothing
    max_disk_read_bytes::Union{Nothing, Int64} = nothing
    max_disk_write_bytes::Union{Nothing, Int64} = nothing
    max_rss_bytes::Union{Nothing, Int64} = nothing
    max_vm_size_bytes::Union{Nothing, Int64} = nothing
    node_list::Union{Nothing, String} = nothing
    run_id::Union{Nothing, Int64} = nothing
    slurm_job_id::Union{Nothing, String} = nothing
    workflow_id::Union{Nothing, Int64} = nothing

    function SlurmStatsModel(attempt_id, ave_cpu_seconds, id, job_id, max_disk_read_bytes, max_disk_write_bytes, max_rss_bytes, max_vm_size_bytes, node_list, run_id, slurm_job_id, workflow_id, )
        o = new(attempt_id, ave_cpu_seconds, id, job_id, max_disk_read_bytes, max_disk_write_bytes, max_rss_bytes, max_vm_size_bytes, node_list, run_id, slurm_job_id, workflow_id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SlurmStatsModel

const _property_types_SlurmStatsModel = Dict{Symbol,String}(Symbol("attempt_id")=>"Int64", Symbol("ave_cpu_seconds")=>"Float64", Symbol("id")=>"Int64", Symbol("job_id")=>"Int64", Symbol("max_disk_read_bytes")=>"Int64", Symbol("max_disk_write_bytes")=>"Int64", Symbol("max_rss_bytes")=>"Int64", Symbol("max_vm_size_bytes")=>"Int64", Symbol("node_list")=>"String", Symbol("run_id")=>"Int64", Symbol("slurm_job_id")=>"String", Symbol("workflow_id")=>"Int64", )
OpenAPI.property_type(::Type{ SlurmStatsModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SlurmStatsModel[name]))}

function OpenAPI.check_required(o::SlurmStatsModel)
    o.attempt_id === nothing && (return false)
    o.job_id === nothing && (return false)
    o.run_id === nothing && (return false)
    o.workflow_id === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SlurmStatsModel)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("attempt_id"), o.attempt_id)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("ave_cpu_seconds"), o.ave_cpu_seconds)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("id"), o.id)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("job_id"), o.job_id)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("max_disk_read_bytes"), o.max_disk_read_bytes)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("max_disk_write_bytes"), o.max_disk_write_bytes)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("max_rss_bytes"), o.max_rss_bytes)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("max_vm_size_bytes"), o.max_vm_size_bytes)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("node_list"), o.node_list)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("run_id"), o.run_id)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("slurm_job_id"), o.slurm_job_id)
    OpenAPI.validate_property(SlurmStatsModel, Symbol("workflow_id"), o.workflow_id)
end

function OpenAPI.validate_property(::Type{ SlurmStatsModel }, name::Symbol, val)

    if name === Symbol("attempt_id")
        OpenAPI.validate_param(name, "SlurmStatsModel", :format, val, "int64")
    end

    if name === Symbol("ave_cpu_seconds")
        OpenAPI.validate_param(name, "SlurmStatsModel", :format, val, "double")
    end

    if name === Symbol("id")
        OpenAPI.validate_param(name, "SlurmStatsModel", :format, val, "int64")
    end

    if name === Symbol("job_id")
        OpenAPI.validate_param(name, "SlurmStatsModel", :format, val, "int64")
    end

    if name === Symbol("max_disk_read_bytes")
        OpenAPI.validate_param(name, "SlurmStatsModel", :format, val, "int64")
    end

    if name === Symbol("max_disk_write_bytes")
        OpenAPI.validate_param(name, "SlurmStatsModel", :format, val, "int64")
    end

    if name === Symbol("max_rss_bytes")
        OpenAPI.validate_param(name, "SlurmStatsModel", :format, val, "int64")
    end

    if name === Symbol("max_vm_size_bytes")
        OpenAPI.validate_param(name, "SlurmStatsModel", :format, val, "int64")
    end


    if name === Symbol("run_id")
        OpenAPI.validate_param(name, "SlurmStatsModel", :format, val, "int64")
    end


    if name === Symbol("workflow_id")
        OpenAPI.validate_param(name, "SlurmStatsModel", :format, val, "int64")
    end
end
