# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""JobCompletionError

    JobCompletionError(;
        job_id=nothing,
        message=nothing,
    )

    - job_id::Int64
    - message::String
"""
Base.@kwdef mutable struct JobCompletionError <: OpenAPI.APIModel
    job_id::Union{Nothing, Int64} = nothing
    message::Union{Nothing, String} = nothing

    function JobCompletionError(job_id, message, )
        o = new(job_id, message, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type JobCompletionError

const _property_types_JobCompletionError = Dict{Symbol,String}(Symbol("job_id")=>"Int64", Symbol("message")=>"String", )
OpenAPI.property_type(::Type{ JobCompletionError }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_JobCompletionError[name]))}

function OpenAPI.check_required(o::JobCompletionError)
    o.job_id === nothing && (return false)
    o.message === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::JobCompletionError)
    OpenAPI.validate_property(JobCompletionError, Symbol("job_id"), o.job_id)
    OpenAPI.validate_property(JobCompletionError, Symbol("message"), o.message)
end

function OpenAPI.validate_property(::Type{ JobCompletionError }, name::Symbol, val)

    if name === Symbol("job_id")
        OpenAPI.validate_param(name, "JobCompletionError", :format, val, "int64")
    end

end
