# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListJobFileRelationshipsResponse

    ListJobFileRelationshipsResponse(;
        count=nothing,
        has_more=nothing,
        items=nothing,
        max_limit=nothing,
        offset=nothing,
        total_count=nothing,
    )

    - count::Int64
    - has_more::Bool
    - items::Vector{JobFileRelationshipModel}
    - max_limit::Int64
    - offset::Int64
    - total_count::Int64
"""
Base.@kwdef mutable struct ListJobFileRelationshipsResponse <: OpenAPI.APIModel
    count::Union{Nothing, Int64} = nothing
    has_more::Union{Nothing, Bool} = nothing
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobFileRelationshipModel} }
    max_limit::Union{Nothing, Int64} = nothing
    offset::Union{Nothing, Int64} = nothing
    total_count::Union{Nothing, Int64} = nothing

    function ListJobFileRelationshipsResponse(count, has_more, items, max_limit, offset, total_count, )
        o = new(count, has_more, items, max_limit, offset, total_count, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ListJobFileRelationshipsResponse

const _property_types_ListJobFileRelationshipsResponse = Dict{Symbol,String}(Symbol("count")=>"Int64", Symbol("has_more")=>"Bool", Symbol("items")=>"Vector{JobFileRelationshipModel}", Symbol("max_limit")=>"Int64", Symbol("offset")=>"Int64", Symbol("total_count")=>"Int64", )
OpenAPI.property_type(::Type{ ListJobFileRelationshipsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListJobFileRelationshipsResponse[name]))}

function OpenAPI.check_required(o::ListJobFileRelationshipsResponse)
    o.count === nothing && (return false)
    o.has_more === nothing && (return false)
    o.items === nothing && (return false)
    o.max_limit === nothing && (return false)
    o.offset === nothing && (return false)
    o.total_count === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ListJobFileRelationshipsResponse)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("count"), o.count)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("has_more"), o.has_more)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("items"), o.items)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("max_limit"), o.max_limit)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("offset"), o.offset)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("total_count"), o.total_count)
end

function OpenAPI.validate_property(::Type{ ListJobFileRelationshipsResponse }, name::Symbol, val)

    if name === Symbol("count")
        OpenAPI.validate_param(name, "ListJobFileRelationshipsResponse", :format, val, "int64")
    end



    if name === Symbol("max_limit")
        OpenAPI.validate_param(name, "ListJobFileRelationshipsResponse", :format, val, "int64")
    end

    if name === Symbol("offset")
        OpenAPI.validate_param(name, "ListJobFileRelationshipsResponse", :format, val, "int64")
    end

    if name === Symbol("total_count")
        OpenAPI.validate_param(name, "ListJobFileRelationshipsResponse", :format, val, "int64")
    end
end
