# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.12.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ComputeNodeModel(BaseModel):
    """
    ComputeNodeModel
    """ # noqa: E501
    compute_node_type: StrictStr
    duration_seconds: Optional[Union[StrictFloat, StrictInt]] = None
    hostname: StrictStr
    id: Optional[StrictInt] = None
    is_active: Optional[StrictBool] = None
    memory_gb: Union[StrictFloat, StrictInt]
    num_cpus: StrictInt
    num_gpus: StrictInt
    num_nodes: StrictInt
    pid: StrictInt
    scheduler: Optional[Any] = None
    scheduler_config_id: Optional[StrictInt] = None
    start_time: StrictStr
    time_limit: Optional[StrictStr] = None
    workflow_id: StrictInt
    __properties: ClassVar[List[str]] = ["compute_node_type", "duration_seconds", "hostname", "id", "is_active", "memory_gb", "num_cpus", "num_gpus", "num_nodes", "pid", "scheduler", "scheduler_config_id", "start_time", "time_limit", "workflow_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComputeNodeModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if duration_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.duration_seconds is None and "duration_seconds" in self.model_fields_set:
            _dict['duration_seconds'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if is_active (nullable) is None
        # and model_fields_set contains the field
        if self.is_active is None and "is_active" in self.model_fields_set:
            _dict['is_active'] = None

        # set to None if scheduler (nullable) is None
        # and model_fields_set contains the field
        if self.scheduler is None and "scheduler" in self.model_fields_set:
            _dict['scheduler'] = None

        # set to None if scheduler_config_id (nullable) is None
        # and model_fields_set contains the field
        if self.scheduler_config_id is None and "scheduler_config_id" in self.model_fields_set:
            _dict['scheduler_config_id'] = None

        # set to None if time_limit (nullable) is None
        # and model_fields_set contains the field
        if self.time_limit is None and "time_limit" in self.model_fields_set:
            _dict['time_limit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComputeNodeModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compute_node_type": obj.get("compute_node_type"),
            "duration_seconds": obj.get("duration_seconds"),
            "hostname": obj.get("hostname"),
            "id": obj.get("id"),
            "is_active": obj.get("is_active"),
            "memory_gb": obj.get("memory_gb"),
            "num_cpus": obj.get("num_cpus"),
            "num_gpus": obj.get("num_gpus"),
            "num_nodes": obj.get("num_nodes"),
            "pid": obj.get("pid"),
            "scheduler": obj.get("scheduler"),
            "scheduler_config_id": obj.get("scheduler_config_id"),
            "start_time": obj.get("start_time"),
            "time_limit": obj.get("time_limit"),
            "workflow_id": obj.get("workflow_id")
        })
        return _obj
