# coding: utf-8

"""
    torc

    Defines the API for the torc service.

    The version of the OpenAPI document: v0.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JobUserDataRelationshipModel(BaseModel):
    """
    Represents a job-user_data relationship showing producer and consumer jobs for user_data.
    """ # noqa: E501
    user_data_id: StrictInt = Field(description="The user_data ID")
    user_data_name: StrictStr = Field(description="The name of the user_data")
    producer_job_id: Optional[StrictInt] = Field(default=None, description="The job that produces this user_data (null for workflow inputs)")
    producer_job_name: Optional[StrictStr] = Field(default=None, description="The name of the job that produces this user_data")
    consumer_job_id: Optional[StrictInt] = Field(default=None, description="The job that consumes this user_data (null for workflow outputs)")
    consumer_job_name: Optional[StrictStr] = Field(default=None, description="The name of the job that consumes this user_data")
    workflow_id: StrictInt = Field(description="The workflow containing the user_data and jobs")
    __properties: ClassVar[List[str]] = ["user_data_id", "user_data_name", "producer_job_id", "producer_job_name", "consumer_job_id", "consumer_job_name", "workflow_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobUserDataRelationshipModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if producer_job_id (nullable) is None
        # and model_fields_set contains the field
        if self.producer_job_id is None and "producer_job_id" in self.model_fields_set:
            _dict['producer_job_id'] = None

        # set to None if producer_job_name (nullable) is None
        # and model_fields_set contains the field
        if self.producer_job_name is None and "producer_job_name" in self.model_fields_set:
            _dict['producer_job_name'] = None

        # set to None if consumer_job_id (nullable) is None
        # and model_fields_set contains the field
        if self.consumer_job_id is None and "consumer_job_id" in self.model_fields_set:
            _dict['consumer_job_id'] = None

        # set to None if consumer_job_name (nullable) is None
        # and model_fields_set contains the field
        if self.consumer_job_name is None and "consumer_job_name" in self.model_fields_set:
            _dict['consumer_job_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobUserDataRelationshipModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_data_id": obj.get("user_data_id"),
            "user_data_name": obj.get("user_data_name"),
            "producer_job_id": obj.get("producer_job_id"),
            "producer_job_name": obj.get("producer_job_name"),
            "consumer_job_id": obj.get("consumer_job_id"),
            "consumer_job_name": obj.get("consumer_job_name"),
            "workflow_id": obj.get("workflow_id")
        })
        return _obj


