# coding: utf-8

"""
    torc

    Defines the API for the torc service.

    The version of the OpenAPI document: v0.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class JobStatus(str, Enum):
    """
    Job statuses
    """

    """
    allowed enum values
    """
    UNINITIALIZED = 'uninitialized'
    BLOCKED = 'blocked'
    READY = 'ready'
    PENDING = 'pending'
    RUNNING = 'running'
    COMPLETED = 'completed'
    FAILED = 'failed'
    CANCELED = 'canceled'
    TERMINATED = 'terminated'
    DISABLED = 'disabled'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JobStatus from a JSON string"""
        return cls(json.loads(json_str))


