# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ResourceRequirementsModel(BaseModel):
    """
    ResourceRequirementsModel
    """ # noqa: E501
    id: Optional[StrictInt] = None
    memory: Optional[StrictStr] = '1m'
    name: StrictStr
    num_cpus: Optional[StrictInt] = 1
    num_gpus: Optional[StrictInt] = 0
    num_nodes: Optional[StrictInt] = 1
    runtime: Optional[StrictStr] = 'PT1M'
    workflow_id: StrictInt
    __properties: ClassVar[List[str]] = ["id", "memory", "name", "num_cpus", "num_gpus", "num_nodes", "runtime", "workflow_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceRequirementsModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceRequirementsModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "memory": obj.get("memory") if obj.get("memory") is not None else '1m',
            "name": obj.get("name"),
            "num_cpus": obj.get("num_cpus") if obj.get("num_cpus") is not None else 1,
            "num_gpus": obj.get("num_gpus") if obj.get("num_gpus") is not None else 0,
            "num_nodes": obj.get("num_nodes") if obj.get("num_nodes") is not None else 1,
            "runtime": obj.get("runtime") if obj.get("runtime") is not None else 'PT1M',
            "workflow_id": obj.get("workflow_id")
        })
        return _obj


