# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WorkflowActionModel(BaseModel):
    """
    WorkflowActionModel
    """ # noqa: E501
    action_config: Optional[Any]
    action_type: StrictStr
    executed: Optional[StrictBool] = False
    executed_at: Optional[StrictStr] = None
    executed_by: Optional[StrictInt] = None
    id: Optional[StrictInt] = None
    is_recovery: Optional[StrictBool] = False
    job_ids: Optional[List[StrictInt]] = None
    persistent: Optional[StrictBool] = False
    required_triggers: Optional[StrictInt] = 1
    trigger_count: Optional[StrictInt] = 0
    trigger_type: StrictStr
    workflow_id: StrictInt
    __properties: ClassVar[List[str]] = ["action_config", "action_type", "executed", "executed_at", "executed_by", "id", "is_recovery", "job_ids", "persistent", "required_triggers", "trigger_count", "trigger_type", "workflow_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowActionModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if action_config (nullable) is None
        # and model_fields_set contains the field
        if self.action_config is None and "action_config" in self.model_fields_set:
            _dict['action_config'] = None

        # set to None if executed_at (nullable) is None
        # and model_fields_set contains the field
        if self.executed_at is None and "executed_at" in self.model_fields_set:
            _dict['executed_at'] = None

        # set to None if executed_by (nullable) is None
        # and model_fields_set contains the field
        if self.executed_by is None and "executed_by" in self.model_fields_set:
            _dict['executed_by'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if job_ids (nullable) is None
        # and model_fields_set contains the field
        if self.job_ids is None and "job_ids" in self.model_fields_set:
            _dict['job_ids'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowActionModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action_config": obj.get("action_config"),
            "action_type": obj.get("action_type"),
            "executed": obj.get("executed") if obj.get("executed") is not None else False,
            "executed_at": obj.get("executed_at"),
            "executed_by": obj.get("executed_by"),
            "id": obj.get("id"),
            "is_recovery": obj.get("is_recovery") if obj.get("is_recovery") is not None else False,
            "job_ids": obj.get("job_ids"),
            "persistent": obj.get("persistent") if obj.get("persistent") is not None else False,
            "required_triggers": obj.get("required_triggers") if obj.get("required_triggers") is not None else 1,
            "trigger_count": obj.get("trigger_count") if obj.get("trigger_count") is not None else 0,
            "trigger_type": obj.get("trigger_type"),
            "workflow_id": obj.get("workflow_id")
        })
        return _obj


