# coding: utf-8

"""
    torc

    Rust-owned OpenAPI surface for Torc.

    The version of the OpenAPI document: 0.12.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WorkflowModel(BaseModel):
    """
    WorkflowModel
    """ # noqa: E501
    compute_node_expiration_buffer_seconds: Optional[StrictInt] = None
    compute_node_ignore_workflow_completion: Optional[StrictBool] = None
    compute_node_min_time_for_new_jobs_seconds: Optional[StrictInt] = None
    compute_node_wait_for_healthy_database_minutes: Optional[StrictInt] = None
    compute_node_wait_for_new_jobs_seconds: Optional[StrictInt] = None
    description: Optional[StrictStr] = None
    enable_ro_crate: Optional[StrictBool] = None
    execution_config: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    metadata: Optional[StrictStr] = None
    name: StrictStr
    project: Optional[StrictStr] = None
    resource_monitor_config: Optional[StrictStr] = None
    slurm_config: Optional[StrictStr] = None
    slurm_defaults: Optional[StrictStr] = None
    status_id: Optional[StrictInt] = None
    timestamp: Optional[StrictStr] = None
    use_pending_failed: Optional[StrictBool] = None
    user: StrictStr
    __properties: ClassVar[List[str]] = ["compute_node_expiration_buffer_seconds", "compute_node_ignore_workflow_completion", "compute_node_min_time_for_new_jobs_seconds", "compute_node_wait_for_healthy_database_minutes", "compute_node_wait_for_new_jobs_seconds", "description", "enable_ro_crate", "execution_config", "id", "metadata", "name", "project", "resource_monitor_config", "slurm_config", "slurm_defaults", "status_id", "timestamp", "use_pending_failed", "user"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if compute_node_expiration_buffer_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_expiration_buffer_seconds is None and "compute_node_expiration_buffer_seconds" in self.model_fields_set:
            _dict['compute_node_expiration_buffer_seconds'] = None

        # set to None if compute_node_ignore_workflow_completion (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_ignore_workflow_completion is None and "compute_node_ignore_workflow_completion" in self.model_fields_set:
            _dict['compute_node_ignore_workflow_completion'] = None

        # set to None if compute_node_min_time_for_new_jobs_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_min_time_for_new_jobs_seconds is None and "compute_node_min_time_for_new_jobs_seconds" in self.model_fields_set:
            _dict['compute_node_min_time_for_new_jobs_seconds'] = None

        # set to None if compute_node_wait_for_healthy_database_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_wait_for_healthy_database_minutes is None and "compute_node_wait_for_healthy_database_minutes" in self.model_fields_set:
            _dict['compute_node_wait_for_healthy_database_minutes'] = None

        # set to None if compute_node_wait_for_new_jobs_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.compute_node_wait_for_new_jobs_seconds is None and "compute_node_wait_for_new_jobs_seconds" in self.model_fields_set:
            _dict['compute_node_wait_for_new_jobs_seconds'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if enable_ro_crate (nullable) is None
        # and model_fields_set contains the field
        if self.enable_ro_crate is None and "enable_ro_crate" in self.model_fields_set:
            _dict['enable_ro_crate'] = None

        # set to None if execution_config (nullable) is None
        # and model_fields_set contains the field
        if self.execution_config is None and "execution_config" in self.model_fields_set:
            _dict['execution_config'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if project (nullable) is None
        # and model_fields_set contains the field
        if self.project is None and "project" in self.model_fields_set:
            _dict['project'] = None

        # set to None if resource_monitor_config (nullable) is None
        # and model_fields_set contains the field
        if self.resource_monitor_config is None and "resource_monitor_config" in self.model_fields_set:
            _dict['resource_monitor_config'] = None

        # set to None if slurm_config (nullable) is None
        # and model_fields_set contains the field
        if self.slurm_config is None and "slurm_config" in self.model_fields_set:
            _dict['slurm_config'] = None

        # set to None if slurm_defaults (nullable) is None
        # and model_fields_set contains the field
        if self.slurm_defaults is None and "slurm_defaults" in self.model_fields_set:
            _dict['slurm_defaults'] = None

        # set to None if status_id (nullable) is None
        # and model_fields_set contains the field
        if self.status_id is None and "status_id" in self.model_fields_set:
            _dict['status_id'] = None

        # set to None if timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp is None and "timestamp" in self.model_fields_set:
            _dict['timestamp'] = None

        # set to None if use_pending_failed (nullable) is None
        # and model_fields_set contains the field
        if self.use_pending_failed is None and "use_pending_failed" in self.model_fields_set:
            _dict['use_pending_failed'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compute_node_expiration_buffer_seconds": obj.get("compute_node_expiration_buffer_seconds"),
            "compute_node_ignore_workflow_completion": obj.get("compute_node_ignore_workflow_completion"),
            "compute_node_min_time_for_new_jobs_seconds": obj.get("compute_node_min_time_for_new_jobs_seconds"),
            "compute_node_wait_for_healthy_database_minutes": obj.get("compute_node_wait_for_healthy_database_minutes"),
            "compute_node_wait_for_new_jobs_seconds": obj.get("compute_node_wait_for_new_jobs_seconds"),
            "description": obj.get("description"),
            "enable_ro_crate": obj.get("enable_ro_crate"),
            "execution_config": obj.get("execution_config"),
            "id": obj.get("id"),
            "metadata": obj.get("metadata"),
            "name": obj.get("name"),
            "project": obj.get("project"),
            "resource_monitor_config": obj.get("resource_monitor_config"),
            "slurm_config": obj.get("slurm_config"),
            "slurm_defaults": obj.get("slurm_defaults"),
            "status_id": obj.get("status_id"),
            "timestamp": obj.get("timestamp"),
            "use_pending_failed": obj.get("use_pending_failed"),
            "user": obj.get("user")
        })
        return _obj
